language: python
python:
- '2.7'

before_install:
    - pip install coveralls
    - pip install -r test_requirements.txt --extra-index-url https://testpypi.python.org/pypi

install:
    - pip install -r requirements.txt --extra-index-url https://testpypi.python.org/pypi

script:
    - python setup.py install
    - nosetests --with-coverage --cover-package=cloudshell/tg/breaking_point --ignore-files='.*bp_exception\.py' --ignore-files='.*exceptions\.py'

after_success:
    - coveralls
